### ISSUE TITLE
Not working in 3.3 - header files not finding header files

### ISSUE THREAD

**Issue by GeminiSquishGames** [SIsilicon/GDNative-Helper#12]
I'm not able to build without errors where header files cannot find other header files. So I have to copy these into the directory the header file looking for the file is... 

C:\Users\lintp\AppData\Roaming\Godot\godot-cpp\include\core\Godot.hpp(7): fatal error C1083: Cannot open include file: 'gdnative_api_struct.gen.h': No such file or directory

The files are available, just not in a location where the Scons file is pointing to apparently. Did the way paths work change in 3.3? That's the only thing I can think of. I can't use it if I have to copy the files around that's too much of a hack.
